### ISSUE TITLE
Consider what the best method would be of storing the dictionary (at present it is a text file, but a Database might be better, then again maybe not, and databases can be a little 麻烦)

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#10]
As title. I think the most important thing to bear in mind will be access times. While we could sort the text file/array by pinyin OR hanzi (two very different orderings), allowing a binary search, searching by anything else might end up being linear. We could create two separate ordered lists, one for hanzi, the other for pinyin, one linking to the other, and then perhaps some sort of hashing for English (as each word has multiple definitions, so alphabetical sorting would be infeasible).

**Comment by IdiosApps** [comment]
I think this is an implementation detail we will come across when we need to
