### ISSUE TITLE
Custom colouring of tones in card's HTML format

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#12]
Some users may find it beneficial to choose the colours used for pinyin and characters. At the moment, this can be done by going into the card's formatting and changing the HTML. 

If we can find how to create a complete .apkg file, then it may be possible to add a colour-selection element to a GUI - where the user could define the colours they'd like to use for each of the tones.

**Comment by danielat998** [comment]
We could also include some predefined colour sets, for example, Pleco default colour scheme.

**Comment by IdiosApps** [comment]
Adds complexity to UI and isn't a super important feature. nice to have, can add when requested
