### ISSUE TITLE
Filtering words which are not in HSK-X but are at HSK-X level

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#14]
For example, the word 留学生 is not in the HSK1-6 lists of vocabulary, although 留学 and 学生 are. 

If there is an excessive number of these, then it may be better for these to be filtered out (thus preventing the users from having to delete these cards from their Anki deck). If a filter were used, having it be optional could be helpful.

Creating this list manually could be a lot of work. Would there be some intelligent way to do it? 
Perhaps the following algorithm could be trialled:
- If (simplified) character combination is not included in HSK1 to HSK-X, then see if the individual characters are. If all of them are included in HSK1 to HSK-X, then omit this character combination from vocabulary items to be added to Anki.

**Comment by danielat998** [comment]
> If (simplified) character combination is not included in HSK1 to HSK-X, then see if the individual characters are. If all of them are included in HSK1 to HSK-X, then omit this character combination from vocabulary items to be added to Anki.

Possible, but I think we would end up with almost nothing left. About half (I guess) of the HSK5/6 vocabulary is different two letter combinations one the learner will already have seen, most of which are not obvious.

> For example, the word 留学生 is not in the HSK1-6 lists of vocabulary, although 留学 and 学生 are.

We could look just at 3(+) character words and omit the word if it contains at least one two-character word (or two two-character words, depending on which produces the best output. We could also think about other rules, e.g. <char><char>人,or <有,上，下，把,不, ...><char>+, but in practise, at least based on my testing, this will only produce very few results, some of whose meanings will be subtly different from what one might expect anyway.
>Creating this list manually could be a lot of work. Would there be some intelligent way to do it?

We could semi-automate it, for example, collect a large body of input text, apply some or all of the above rules, and then examine the output by hand, removing anything that needs removing. Or alternatively, iterate through all the words in the dictionary and use that as the input.
