### ISSUE TITLE
Convert input text to Memrise output

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#16]
According to http://feedback.memrise.com/knowledgebase/articles/525095-add-words-to-my-course-or-upload-words-from-a-spre , 
- there is a limit of 1000 words. 
- tab/comma delimiting can be used for words
- new line/semicolon delimiting can be used for lines

**Comment by james-clark-5** [comment]
I think the only difference between outputting for Anki and Memrise is in the DeckFactory.java deckGenerator code: "getPinyinWithHTML" should be just "getPinyin".

In terms of the UI, having a radio button to choose between Anki and Memrise would do the trick in a clean manner. If we have more outputs later on, we could use a drop-down menu.

**Comment by danielat998** [comment]
I think another difference will be that the only columns (At least for now) that we want will be chinese name and definition (maybe pinyin too, though I guess we'd want to merge this with definition?). I am unsure whether memrise lets you define your own columns.

**Comment by james-clark-5** [comment]
I think you're right, Daniel. Perhaps we can use a new line to separate definition&pinyin, whilst keeping them in the same field (may need semicolon delimiting then). We'll just have to experiment and see what works!

**Comment by IdiosApps** [comment]
Haven't used Memrise for years; can look back into this if it comes up organically
