### ISSUE TITLE
Add support for other languages

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#17]
Obviously not a high priority for now, but this should be fairly straightforward, assuming appropriate dictionaries could be found. Latin based languages are just delimited by spaces, although it may be necessary to remove affixes and so on, depending on what the dictionary contains.

Also, slightly easier, we could add support for Chinese -<other language> dictionaries, for example, CFDICT, ChE-DICC, CHDICT, as well as Cantonese dictionaries. These could well be in an identical format to CC-CEDICT, in which case, it would be as simple as just just pointing to a different dictionary file.

If we do this, we will have to consider including some sort of download manager, as dictionaries are not small files.

**Comment by IdiosApps** [comment]
I think this would come later - we'd need dictionary packages for each language (possibly made by us, so we can make the format correct - time consuming!) and to make H2A much more generalised. For now, we should stay focused.
