### ISSUE TITLE
Option to extract Wechat messages automatically and create flashcards from them

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#18]
It goes without saying that for privacy reasons, this would not be enabled by default, but could be an invaluable tool for learning. This would also require an Android App to be written, which has not been done yet, but was definitely on the cards anyway.

  There exist projects such as the following:https://github.com/ppwwyyxx/wechat-dump that do this. This could potentially either be integrated directly (no idea how difficult, or even possible Python on Android is), or maybe rewritten in Java first. There may also exist other similar projects of which I am unaware that would be more amenable for Android integration (i.e. written in Java).

**Comment by james-clark-5** [comment]
A useful option would be to delete any extracted txt files once the Anki deck has been produced, if the user wishes.

**Comment by IdiosApps** [comment]
Let users do this themselves. We don't want to be touching their data
