### ISSUE TITLE
Sort out the build environment etc

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#19]
We should do the following:
* Restructure the code into directories and packages
* Create unit tests
* Create build scripts (Gradle perhaps?), and possibly also configure to work nicely with an IDE

**Comment by james-clark-5** [comment]
Are things configured to the IntelliJ IDEA IDE now?

**Comment by danielat998** [comment]
well it seems to work for me...

**Comment by IdiosApps** [comment]
@danielt998 things running smoothly with Gradle structure, JDK14 with preview language features, JUnit, etc.?

**Comment by danielt998** [comment]
still a few things left (more unit tests + restructure code) here but gonna close this as they don't really relate to the build env
