### ISSUE TITLE
Support for printed flashcards

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#21]
A little random, but another potential addition, I don't think it would be hard at all (Java 2DGraphics could be used I think, like I did with this project here (https://github.com/danielat998/poster)

**Comment by IdiosApps** [comment]
Yeah this would be nice. What features would you want?

- Number of flashcards per page 
- Different page sizes (A4, A5)
- Colour / black&white (tones)
- Fonts

**Comment by danielt998** [comment]
Maybe do some market research...

**Comment by IdiosApps** [comment]
Think this would be a spin-off project
