### ISSUE TITLE
BookToAnki

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#24]
Scan image, use OCR on text, extract characters 

Crazy adaptation:
Apply OCR to video feed, of a GoPro of someone in China (sort by frequency)

**Comment by IdiosApps** [comment]
I think to get quality flashcards that accurately reflect the source text, OCR may not be good enough (artefacts, OCR failures, image processing libraries, OCR library etc. needed). 

I don't think anyone is going to photograph their textbook then make flashcards from it.

@danielt998 shall we close this as not going to be implemented?

**Comment by danielt998** [comment]
I kind of disagree, still think this could be useful sorry (doesn't necessarily matter if OCR is not 100%)

**Comment by IdiosApps** [comment]
In that case we should probably go with http://tess4j.sourceforge.net/ (Apache License 2.0)

If we're hosting on a server, we should ask users if their test is simplified, traditional, or mixed - detection would use a quite of resources, and to serve more users we'd need to make each interaction as lightweight as possible.

**Comment by danielt998** [comment]
How computationally expensive is OCR? And would using a frontend library for that be an option?

**Comment by IdiosApps** [comment]
https://github.com/naptha/tesseract.js/blob/master/README.md apparently runs either in browser or in node

OCR could be several seconds per A4 page, one page per thread. Could be slow if many users try to OCR many docs at the same time. Could email them when done if queue is long.

**Comment by danielt998** [comment]
yeah then I don't know, it would really depend on what server capacity we had if we were to produce a web frontend. We could still implement for the desktop app though :)

**Comment by IdiosApps** [comment]
leave OCR to the users, or another repo. Out of scope for H2A
