### ISSUE TITLE
Open source database of additional information for words

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#28]
While CEDICT is great, the amount of information it contains is a little minimal, for example, the following would be nice to have (not necessarily just for this project, but in general too):
* Pronunciation (maybe both male+female?)
* Example sentences
* Components of the character ??
* Stroke order ?
* Other grammatical information, e.g. whether it is a noun/adjective/verb/... - in some cases, this may be mentioned in CEDICT, but in an unstructured format - maybe we could extract this somehow
* British English (or other Englishes) replacements for some translations - this could be semi-automated relatively quickly I think, and we can just maintain a list of words that are 'different', making sure that we have a way to update them as the default ones get updated
* [**feel free to add suggestions here**]

Some of this information may already exist, so we should definitely do some research before duplicating any effort.

Many of these do exist, but non-freely licensed. In some cases, we may be able to use this information, depending on the licence, but an open resource would still be nice.

Obviously this would be a huge undertaking, but the first step would be to create a place to store the data, e.g. a Git repo, and then maybe publicise it to people who might be interested. CC-CEDICT also has a nice Web UI for creating entries, which is something we could possibly mimic, for people not too comfortable with Git.

Also, having this information, even just for e.g. the 1000 most common words would still be invaluable, it does not have to be 'complete' to be useful.

**Comment by danielat998** [comment]
It seems the MDBG project (the project behind of CC-CEDICT) has some way to get some of this information on their website, however, I am unable to see how to extract it nor where it comes from/how it is licensed

**Comment by danielat998** [comment]
I propose something like the following to get us started, though possibly with separate delimiters (we will likely need two delimiters. We can add fields as time goes on:
颜色|en-UK:colour;en-AU:colour;en-CA:colour|n|我喜欢这个颜色。这是一个颜色。
That is,:
*simplified word for reference (corresponds to a single CC-CEDICT entry)
*localised translations - need to be very careful with delimiters here...
*word type(s)
*example sentences, one after the other

**Comment by james-clark-5** [comment]
Having the option to store the sentence the character was extracted from in the Anki output could be helpful (very context specific - too specific?) and personal (though perhaps a bit too personal? Optional, though!).

**Comment by james-clark-5** [comment]
I have information about stroke order/animations from Gabor Ugray; I'll comment some info when I've had a gander.

**Comment by IdiosApps** [comment]
@danielt998 did this in in another repo (don't know which)
