### ISSUE TITLE
Producing voice clips 

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#29]
It would be interesting to scan all the CC-CEDICT words (or the 2000 most frequent words) to find how many unique sound recordings would be required. 

Having recordings for all the initials and finals (with all tones) would likely account for a huge number of the recordings needed (single-character CC-CEDICT entries), and shouldn't be too time consuming for a native speaker to record. 

You could either store the sounds with the CC-CEDICT entries, or grab them based on the numbered pinyin in the CC-CEDICT entries - the latter is probably more efficient (avoids much duplication). 

I think this would be a great first step. Of course, recording combinations of characters would be needed for many Chinese words. 

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by danielat998** [comment]
http://www.yellowbridge.com/chinese/pinyin-combo.php
So presumably just all of these, with all 5 possible tones (including neutral tone). In theory, we could then just combine these, but this would not be ideal because a) it might not flow too naturally and b)sometimes tones change based on the syllables before/after it.

**Comment by james-clark-5** [comment]
@danielat998 I think it'd be better to make 2+ character audio clips unique. See the next issue I made for an idea on how to do this. 

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by danielat998** [comment]
Agreed

**Comment by IdiosApps** [comment]
I think this is quite a solid feature to try and get in our next sprint - could add a lot of value to the flashcards if:

-  we can get a good audio library so sound clips are actually useful

- said library has suitable licensing

- can store audio clips in Anki/Pleco/Memrise decks

**Comment by IdiosApps** [comment]
out of scope
