### ISSUE TITLE
Recording voice clips for words with 2+ characters 

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#30]
A simple website may be an efficient collect voice clips for 2+ character words. To elaborate:

* Show the user a word, and ask them to either record a word, or listen to a previous recording. If they think the previous recording is of good quality, they could up-vote it. 
* After, say, 1 week, the most up-voted clip could be chosen as the recording of choice. Other clips for the same word could be kept or discarded. 
* This process could be available for Male/Female pronunciation separately. Allow either gender to vote on either gender's recording. 

*Users could be vetted, to prevent trolling, and to ensure that their recording setup is of high enough quality. 

Needs some more ideas to make it a tractable possibility. Could be an effective way to open-source audio clip generation. Would then be easy to extend to other languages - which would help us extend our project to other languages, and would likely help many people with their own projects. 

Please give feedback/critique! 

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by james-clark-5** [comment]
Note: 

Would be very sensible to order the words presented based on their frequency!

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by IdiosApps** [comment]
out of scope
