### ISSUE TITLE
Break characters into components

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#31]
Here is a file (I think for Chinese, Japanese, and Korean - CJK) that gives key components of characters:
* http://cjkdecomp.codeplex.com/

Perhaps we have to extract just the Chinese characters to simplify things, then can sort by simplified Chinese character (or hash).

There's also: 
* https://commons.wikimedia.org/wiki/Commons%3aChinese_characters_decomposition

but I can't currently see how we'd use it.

**Comment by danielat998** [comment]
This could be used as an additional field in the card, as it might help a user learning to write.
