### ISSUE TITLE
Which font(s) to use?

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#33]
To quote Gabor L Ugray: 

* "Zydeo is all about typography, and the font I’m using to display results was probably the one area that received the greatest share of my attention. **Whether or not you’re developing a dictionary yourself, having the right font at hand to write Chinese may be equally important to you**"

from:  https://jealousmarkup.xyz/texts/pc-speak-chinese/

Here is a fantastic intro and some good resources (thanks to Gabor again):
https://jealousmarkup.xyz/texts/chinese-typefaces/

**Comment by james-clark-5** [comment]
If we're not sure which to pick, having a few for the user to choose from (with what we feel best as default) could be good.

**Comment by IdiosApps** [comment]
interface detail we aren't ready to work on
