### ISSUE TITLE
Licences / Repositories/ Sources of information used

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#36]
Should we have a "licences" file which notes what we used, and who made it/where it came from? Can be in a "help->about app" screen.

**Comment by james-clark-5** [comment]
If/when we create an app, this could be handy:

https://github.com/mikepenz/AboutLibraries

**Comment by danielat998** [comment]
yeah that's actually what the original goal of the 'legal' file, though it will need updating/correcting.

**Comment by IdiosApps** [comment]
Closing as we can do this when it comes to it. We just have CC-CEDICT and we're transparent about that.
