### ISSUE TITLE
Produce some useful command line tools for the Chinese language

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#38]
For example, a tool to convert a text in traditional characters to simplified. This should handle standard input/output correctly

**Comment by danielat998** [comment]
This is another example of a place where having a dictionary package that is uncoupled from HAnziToAnki would be nice.

**Comment by IdiosApps** [comment]
We started splitting dictionary stuff to a separate package. It can later become a separate repo which becomes more powerful.
