### ISSUE TITLE
Filter by frequency 

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#4]
Filtering by frequency, and/or by HSK level, could improve usefulness of vocabulary extraction.

**Comment by james-clark-5** [comment]
Here is a list of character frequencies, in various file types (and for various corpuses).

http://lingua.mtsu.edu/chinese-computing/statistics/

**Comment by IdiosApps** [comment]
I think this is a bit redundant as HSK vocab files kinda does this for us. It's not perfect, but good enough so we can focus on other stuff to get more value faster
