### ISSUE TITLE
Some Chinese characters don't display

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#43]
I have noticed that some Chinese characters don't display in the TextField of the GUI. It seems a little random too - for example, '你‘ doesn't show, while '我' does. While this does not cause any functional problems, it would be nice to fix. It could be worth testing on other platforms/set ups to see whether it is a system problem or a code/library/font problem.

**Comment by IdiosApps** [comment]
Not sure we will focus on JavaFX (there will be WAY less javafx devs who want to help than e.g. React devs), and current JavaFX stuff is half baked.
