### ISSUE TITLE
create flashcards for sentence structures

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#44]
Automatically determine the sentence structure(s) required for a given sentence and create flashcards for these.

**Comment by IdiosApps** [comment]
I think it's probably easier for users to use a well-curated grammar wiki, such as https://resources.allsetlearning.com/chinese/grammar/
they probably sell flashcards based around their structure points, and I don't think this feature would give good return on time invested.

@danielt998 You want us to implement this still, or?
