### ISSUE TITLE
Karaoke app

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#47]
Find which Hanzi are known by the user, and display (tone marked) pinyin above unknown characters. 
Would make karaoke much more accessible, and a good learning experience. 

Of course, extendable to other languages.

**Comment by danielt998** [comment]
What would the output format be? Maybe a chunk of text with both Hanzi and pinyin, or are you thinking of sometime producing real-time output? :o

**Comment by IdiosApps** [comment]
Maybe it could go into some software that'll highlight lines from left to right, and sync to some data about when each syllable starts. Needs research!

**Comment by IdiosApps** [comment]
I like the idea of "graded readers" for songs, but this distracts from core domain work so closing the ticket
