### ISSUE TITLE
Look into ways to extract Chinese vocabulary from someone's entrire collection of anki decks

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#5]
If this could be done easily, as well as somehow determining whether a user "knows" the word then we would have a more accurate way of removing words she/he already knows, rather than the somewhat primitive method of removing words that are part of a certain HSK level.

**Comment by james-clark-5** [comment]
This may be of interest (perhaps not directly applicable, though, but still a good starting point): 

http://batterseapower.github.io/pinyin-toolkit/

"Using the Hanzi Graph, you are able to see graphically how far you have come towards each HSK level, and how your knowledge of the Chinese characters has improved over time."

**Comment by IdiosApps** [comment]
scope creep
