### ISSUE TITLE
Ideas for extra fields (please add to)

### ISSUE THREAD

**Issue by danielat998** [danielt998/HanziToAnki#51]
The user should be able to specify what fields they would like, as well as the side of the card on which each of these should be. We should also add support for some additional fields, for example:
* Simplified Hanzi
* Traditional Hanzi
* Meaning - English
* Other languages
* Pinyin
* Other Romanisation systems (I think these could be generated programatically from the pinyin)
* Cantonese pronunciation
* Measure words
* .....

**Comment by IdiosApps** [comment]
We can come back to this when we get feedback/requests from users
