### ISSUE TITLE
Grab all possible definitions from input

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#57]
E.g. we have 中国人, which could be split in the following way:
中国人 (chinese)
中国，人 (china, person)
中，国，人(middle, country, person)

Here's some pseudocode to try and catch all of these possible instances, in the example sentence "ABCD.":

For each character's index in clause/line/paragraph:
look in the dictionary for the word "ABCD", then "ABC", then "AB", then "A"
proceed to "BCD", "BC", "B",
proceed to "CD", "C",
proceed to "D".
If there is a match in the dictionary, save it.

**Comment by danielat998** [comment]
This sounds like a good place for a recursive algorithm...

**Comment by IdiosApps** [comment]
Some pretty juicy recursion code PM'd by Daniel:

Set returnPossibleWords(String fullWord){
  Set theSet=emptySet
  if(fullWord is a word){
    theSet.add(fullWord)
  }
  if(length>1){
    Set.addAll(returnPossibleWords(string.substring(0,length-1)
Set.addAll(returnPossibleWords(string.substring(1,length)  }
}

**Comment by danielat998** [comment]
*pseudocode ;)

**Comment by IdiosApps** [comment]
Works. Will push commits shortly.

**Comment by danielt998** [comment]
worth adding here that 国人 is also a valid word, so this is a perfect example
