### ISSUE TITLE
Possible troubleshooter: check encoding of input file 

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#60]
Saving a .txt file created in NotePad++ gave it UTF-8 encoding - and H2A used to successfully create output.

However, prior to this I created a file in Notepad (baked into Windows). **Somehow Unicode wasn't used in the encoding - I'm trying to repro the problem, but Windows tells me I should save as UTF now!**

So, I created an empty .txt file with notepad, and opened it in IDEA. I added some Chinese characters, and.... the encoding is okay..?

**Summary:**
- Can't reproduce the problem of encoding not being UTF-8, but being UTF-8-BOM (or some other -BOM encoding)
- May be worth checking input file's encoding prior to reading/using its contents.
- Nevertheless, may be worth having a wiki for troubleshooting.

**Comment by IdiosApps** [comment]
For now we assume UTF-8, which should be quite solid.

If lines of text are read in and not matches against our Simp/Trad maps are found, then we log out that there was probably an encoding issue.

Could add encoding detection (ICU), but detectors also need a decent length of input text sometimes. To keep dependencies minimal we could hold off until needed. 

@danielt998 shall we mark as on-hold, or implement as it should be fairly trivial?

**Comment by danielt998** [comment]
I'd say this is low priority as Unicode is pretty ubiquitous (right?) (though I think there's an encoding called Big5 that's popular in China) We should still produce an error message that at least mentions that this could be an encoding issue and only UTF8 is supported maybe? And then we can revisit at a later date. BTW I think 95% of people will be copy/pasting text.

**Comment by IdiosApps** [comment]
https://github.com/danielt998/HanziToAnki/commit/f814248b66567dfbb6182c700bcf1d05b43fb6b5 is the commit that logs out an encoding error message.
