### ISSUE TITLE
Ordering flashcards from "get all word combos" recursive method

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#62]
As of yet, I don't understand why the output words are ordered the way they are!

**Input:**
你好吗
我是山外
豆腐多少钱吗

**Output**
你	you (informal, as opposed to courteous 您[nin2])/	<span class="tone3">nǐ</span>	
豆	bean/pea/CL:棵[ke1],粒[li4]/sacrificial vessel/	<span class="tone4">dòu</span>	
是	variant of 是[shi4]/(used in given names)/	<span class="tone4">shì</span>	
腐	decay/rotten/	<span class="tone3">fǔ</span>	
我	I/me/my/	<span class="tone3">wǒ</span>	
山	mountain/hill/anything that resembles a mountain/CL:座[zuo4]/bundled straw in which silkworms spin cocoons/gable/	<span class="tone1">shān</span>	
少	young/	<span class="tone4">shào</span>	
钱	coin/money/CL:筆|笔[bi3]/unit of weight, one tenth of a tael 兩|两[liang3]/	<span class="tone2">qián</span>	
你好	Hello!/Hi!/How are you?/	<span class="tone3">nǐ</span><span class="tone3">hǎo</span>	
外	outside/in addition/foreign/external/	<span class="tone4">wài</span>	
吗	(question particle for "yes-no" questions)/	<span class="tone5">ma</span>	
多	many/much/often/a lot of/numerous/more/in excess/how (to what extent)/multi-/Taiwan pr. [duo2] when it means "how"/	<span class="tone1">duō</span>	
豆腐	tofu/bean curd/	<span class="tone4">dòu</span><span class="tone5">fu</span>	
多少	how much/how many/which (number)/as much as/	<span class="tone1">duō</span><span class="tone5">shao</span>	
好	to be fond of/to have a tendency to/to be prone to/	<span class="tone4">hào</span>

**Comment by danielat998** [comment]
Due to the implementation of HashSet, you could look into other types of
set/collection maybe?

**Comment by danielt998** [comment]
LinkedHAshSet will preserve insertion order, or we can use TreeSet to store them alphabetically, but  I'm wondering what the value would be of that, and what order would the user prefer?

**Comment by IdiosApps** [comment]
I think storing them in insertion order would be close to ideal; for example, consider the case where a user inputs a song's lyrics - naturally, you'd want to go through the words chronologically and build up from the start of the song. At least, for this use case insertion order would be grand.

**Comment by danielt998** [comment]
I was thinking along the same lines - so feel free to replace all HashSets
with LinkedHashSets. One thing we might want to consider in the future is
support for other orderings, for example, order by frequency of that word
in the text or by the frequency of the word in 'real life' - if we could
find some info on that.

**Comment by IdiosApps** [comment]
Would be a good option - though I guess if a character is frequent in the input then it'll be likely to appear early on, and it may be better to just go with insertion-ordering to make comprehension of a text more smooth. If you go by frequency ordering, you'd be good at skimming through a text to pick out characters - but then you're losing the context of the text.

**Comment by IdiosApps** [comment]
Note: It seems that whilst LinkedHashSet orders items according to insertion and doesn't create duplicate entries, it _replaces_ old entries of context with newer entries.
I think it'd be best if, once an entry is made, it is not replaced - this way you'll have immediate context for e.g. a song, instead of potentially having the context at the end.

**Comment by danielt998** [comment]
I think a better option might be to have multiple "context"s per word and
then display all of the sentences in which a word occurs.

**Comment by IdiosApps** [comment]
@danielt998 probably want to have a default upper limit of 3 context lines. Otherwise things could get messy for those frequent characters!

**Comment by IdiosApps** [comment]
Pseudocode (mostly unsure about making sure Anki knows to put the extra contexts on their own lines):


If (word.context!=null) {
word.setContext(word.getContext() + "\n" + line) 
}

**Comment by IdiosApps** [comment]
How would you count how many lines of context have been added to a word? One (not very nice) way would be to add a "context counter" field to the Word class. Otherwise, you could detect the number of "\n" (or whatever works for Anki in the end)

**Comment by IdiosApps** [comment]
stale
