### ISSUE TITLE
UI/UX ideas

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#7]
- What are the key elements to be shown to the user?
- What are the key buttons that will be needed?
- What additional options/customisations would be helpful?
- Would a start-up/introductory process (select current HSK level, simplified/traditional characters, etc.) be helpful?

**Comment by james-clark-5** [comment]
We'll see what we can whip up in JavaFX for this.

**Comment by IdiosApps** [comment]
> We'll see what we can whip up in JavaFX for this.

not much lol
